server:
  port: 62001
spring:
  application:
    name: sleuth-traceB
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:62100
eureka:
  client:
    service-url:
      defaultZone: http://cmbc:+oNI8PDN4SJ75tybPFatZg==@localhost:20000/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: sleuth-traceA
    description: test