spring:
  application:
    name: eureka-server
  security:
    user:
      name: cmbc
      password: +oNI8PDN4SJ75tybPFatZg==
server:
  port: 20000
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false # 强制关闭服务自保（自动开启服务自保将会失效）
    eviction-interval-timer-in-ms: 30000  #每隔多久触发一次服务剔除
encrypt:
  key: 1234567887654321