server:
  port: 63000
spring:
  application:
    name: stream-sample
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"