spring:
  application:
    name: feign-client
server:
  port: 40005
eureka:
  client:
    service-url:
      defaultZone: http://cmbc:+oNI8PDN4SJ75tybPFatZg==@localhost:20000/eureka/
    instance:
      hostname: localhost